services:
  - type: web
    name: ai-trip-planner-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -y
      export PATH="$HOME/.local/bin:$PATH"
      uv pip install --system -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: openai/gpt-4o-mini
      - key: ARIZE_SPACE_ID
        sync: false
      - key: ARIZE_API_KEY
        sync: false
